version: '3.8'

services:
  service:
    container_name: ${DIR}
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/service
    depends_on:
      - mysql
    env_file:
      - .env
    environment:
      - MYSQL_HOST=${DIR}_mysql_dev
    ports:
      - ${PORT}:${PORT}
    expose:
      - ${PORT}
    command: npm run dev
    networks:
      - internalnet

  mysql:
    container_name: ${DIR}_mysql_dev
    image: mysql:${MYSQL_VER}
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - mysql_dev_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
    expose:
      - ${MYSQL_PORT}
    networks:
      - internalnet

volumes:
  mysql_dev_data: {}

networks:
  internalnet:
    driver: bridge
